name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Test
        run: |
          Get-Process -PID $pid
          $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
          $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
